### ISSUE TITLE
PHP storm 10 support

### ISSUE THREAD

**Issue by florentdestremau** [kosssi/ansible-role-phpstorm#11]

**Comment by kosssi** [comment]
It's for you: https://github.com/kosssi/ansible-role-phpstorm/releases/tag/v2.0.3 :love_letter: ^^

**Comment by kosssi** [comment]
if you can vote for me :smile: https://galaxy.ansible.com/detail#/role/1145

**Comment by florentdestremau** [comment]
Just realized the parameter 10.0 worked, i thought the new download page would break this
:+1:
