### ISSUE TITLE
Role not working

### ISSUE THREAD

**Issue by florentdestremau** [kosssi/ansible-role-phpstorm#12]
Trace:

```

failed: [localhost] => {"dest": "/opt/phpstorm-10.0.2.tar.gz", "failed": true, "item": "", "response": "HTTP Error 403: Forbidden", "state": "absent", "status_code": 403, "url": "http://download.jetbrains.com/webide/PhpStorm-10.0.2.tar.gz"}
msg: Request failed

```

**Comment by florentdestremau** [comment]
Works for version 9 and under but not with 10+

**Comment by kosssi** [comment]
@florentdestremau can you make a PR? :dancer:

**Comment by florentdestremau** [comment]
Can't find a viable download link, I tried this afternoon, no result so far

**Comment by kosssi** [comment]
Thanks @florentdestremau, 

We can ask directly to @jetbrains :smile: 

Have you another link for phpstorm with version number in link ? Like this http://download.jetbrains.com/webide/PhpStorm-10.0.2.tar.gz

Actually we find this but not very good:
- https://download.jetbrains.com/webide/PhpStorm-2016.1.tar.gz
- https://download.jetbrains.com/webide/PhpStorm-2016.1.tar.gz.sha256

Thanks,

**Comment by fubarhouse** [comment]
Is there any chance to get an absolute latest address?

II'd be interested in expanding and making a role for all things JetBrains, but without being able to get the latest version number from the terminal, it seems pointless especially given we've got the JetBrains toolbox app now.

**Comment by emielmolenaar** [comment]
I guess Jetbrains just block direct downloads or downloads from non-browsers for some reason.

**Comment by emielmolenaar** [comment]
Got it fixed by using wget:

```
- name: Download PhpStorm archive for version "{{ phpstorm_version }}"
  command: >
    wget
    --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36"
    --referer="https://www.jetbrains.com/phpstorm/download/download-thanks.html?platform=linux"
    --output-document="{{ phpstorm_archive }}"
    http://download-cf.jetbrains.com/webide/PhpStorm-"{{ phpstorm_version }}".tar.gz
    creates={{ phpstorm_archive }}
  when: phpstorm_exist.stat.exists == False
```

**Comment by fubarhouse** [comment]
I would recommend waiting until toolbox cli tools come into play.
It would be much more convenient to download through the toolbox through command line tools, instead of having overly complicated logic or commands - we could even create custom modules to have something like such:

```
- name: "Install JetBrains products."
   jetbrains:
     product: "{{ item }}"
     version: latest
     location: /Applications
     with_items:
       - phpstorm
       - webstorm
```

Now something like that would be freaking sweet, but the command line API does not exist yet - give it time.
