### ISSUE TITLE
ansible 1.9 unarchive failing but shell command works

### ISSUE THREAD

**Issue by phillpafford** [kosssi/ansible-role-phpstorm#9]
ansible --version
ansible 1.9.0.1

TASK: [nab.phpstorm | Decompress phpStorm archive] **************************** 
fatal: [server] => input file not found at /opt/phpstorm-9.0.tar.gz or /opt/phpstorm-9.0.tar.gz

FATAL: all hosts have already failed -- aborting

### If i use the old method w/ shell it works
    - name: Decompress phpStorm archive
      shell:
        tar xvfz {{ phpstorm_archive }} -C {{ phpstorm_install_dir }}
      when: phpstorm_exist.stat.exists == False

### Does not work
    - name: Decompress phpStorm archive
      unarchive:
        src={{ phpstorm_archive }}
        dest={{ phpstorm_install_dir }}
      when: phpstorm_exist.stat.exists == False

**Comment by kosssi** [comment]
hum bad tripe it's my last refactoring...
Before merge it I test on two laptop.
 
what is your environment and can you execute your playbook with -vvvv please ?

**Comment by kosssi** [comment]
I have the same error now...

**Comment by kosssi** [comment]
@phillpafford the new release is for you ;)

https://github.com/kosssi/ansible-role-phpstorm/releases/tag/v2.0.2
if it's good you can close this issue ?

Thanks for your contribution

**Comment by phillpafford** [comment]
I think it's good, thanks for the fast response!
